### ISSUE TITLE
Błąd w dokumentacji

### ISSUE THREAD

**Issue by pslusarczyk** [MicrosoftDocs/visualstudio-docs.pl-pl#2]
Wbrew temu, co podaje dokumentacja, w Unity Hub nie ma możliwości zainstalowania VS. Na liście komponentów do najnowszej wersji 2018.2 nie ma sekcji Dev Tools ani żadnej innej, która by zawierała VS. Pozdrawiam

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 87f1198e-ec10-c455-9c19-c3b1f042d9c0
* Version Independent ID: 13b99f02-23dc-efcb-43a7-092f74e08290
* Content: [Wprowadzenie do narzędzi Visual Studio Tools for Unity](https://docs.microsoft.com/pl-pl/visualstudio/cross-platform/getting-started-with-visual-studio-tools-for-unity)
* Content Source: [docs/cross-platform/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs.pl-pl/blob/live/docs/cross-platform/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev15**
* GitHub Login: @dantogno
* Microsoft Alias: **v-davian**

**Comment by LisandroSu** [comment]
Witaj @pslusarczyk 

Dziękujemy za opinię. 

Aktywnie przeglądamy Twoje komentarze i wkrótce się do Ciebie odezwiemy. 

Pozdrawiamy, 
Międzynarodowy zespół witryny Microsoft DOCS

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1424](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1424) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Witaj, @pslusarczyk! 
Dziękujemy za Twój wkład. Twoja opinia dotyczy oryginalnej dokumentacji. 
W związku z tym przenosimy ten problem do repozytorium angielskiej wersji językowej. Stan problemu możesz sprawdzić tutaj: https://github.com/MicrosoftDocs/visualstudio-docs/issues/1424. 
Naprawdę doceniamy Twój wkład w nasze artykuły.  
Pozdrawiamy, 
Międzynarodowy zespół witryny Microsoft DOCS
